---
- name: verdaccio installed
  npm:
    name: verdaccio
    version: "{{ verdaccio_version | default(omit) }}"
    global: true
  notify: restart verdaccio

- name: verdaccio plugins installed
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    #path: "{{ verdaccio_pluginsdir }}"
  with_items: "{{ verdaccio_plugins }}"
  when: verdaccio_plugins is not none

- name: verdaccio user created
  user:
    name: verdaccio

- name: resolve npm config path
  command: npm config get prefix --no-update-notifier
  register: npm_config_prefix_resolve
  changed_when: false
  ignore_errors: true

- name: setup npm_config_prefix
  set_fact: npm_config_prefix = "{{ npm_config_prefix_resolve.stdout }}"
  when: >
    (npm_config_prefix_resolve.rc == 0) and
    ("FAILED" not in npm_config_prefix_resolve.stderr) and
    (npm_config_prefix_resolve.stdout | length > 0)

- name: deploy verdaccio systemd unit
  template:
    src: verdaccio.service.j2
    dest: /etc/systemd/system/verdaccio.service
    mode: 0600
  notify:
    - systemd daemon-reload
    - restart verdaccio

- name: verdaccio service enabled
  systemd:
    name: verdaccio
    enabled: true

- name: verdaccio directories creation
  file:
    path: "{{ item }}"
    state: directory
    owner: verdaccio
    mode: 0755
  loop:
    - "{{ verdaccio_datadir }}"
    - "{{ verdaccio_configdir }}"

- name: config deployed
  template:
    src: config.j2
    dest: "{{ verdaccio_configdir }}/verdaccio.yml"
    owner: verdaccio
    mode: 0600
  notify: restart verdaccio

- name: install logrotate script
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/verdaccio
    owner: root
    mode: 0644
